// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SchoolMitAPI.Data;

namespace SchoolMitAPI.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    [Migration("20200508104328_Tas2")]
    partial class Tas2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SchoolMitAPI.Models.TaskManager", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int[]>("Days")
                        .HasColumnType("integer[]");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string[]>("Platforms")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("TaskTaskManager");
                });
#pragma warning restore 612, 618
        }
    }
}
